# Generated by Django 5.0 on 2023-12-27 09:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('duration', models.CharField(max_length=255)),
                ('logo_url', models.URLField(blank=True, max_length=255, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('student_qty', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('active_courses', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('extra_role', models.CharField(blank=True, max_length=50, null=True)),
                ('payments', models.CharField(blank=True, max_length=255, null=True)),
                ('invite_people', models.IntegerField(blank=True, null=True)),
                ('cashback', models.FloatField(blank=True, null=True)),
                ('debt', models.FloatField(blank=True, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tgbot.courses')),
            ],
        ),
    ]
