# Generated by Django 5.0 on 2023-12-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_remove_courses_id_courses_courses_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='courses_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
