# Generated by Django 5.0 on 2024-01-03 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_users_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referrals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('referrals_id', models.IntegerField()),
                ('referral', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='tgbot.users')),
            ],
        ),
    ]
